package test;

import domain.InscripcionEstandar;
import domain.Jugador;
import domain.Participante;
import domain.Partido;
import java.util.Date;

@SuppressWarnings("all")
public class Creaciones {
  public static Partido crearPartidoLlenoCon10Estandar() {
    Date _date = new Date();
    Partido _partido = new Partido(_date);
    Partido partidoEstandar = _partido;
    Jugador _jugador = new Jugador("Pepe", 20);
    InscripcionEstandar _inscripcionEstandar = new InscripcionEstandar();
    Participante _participante = new Participante(_jugador, _inscripcionEstandar);
    Participante part1 = _participante;
    Jugador _jugador_1 = new Jugador("Luis", 35);
    InscripcionEstandar _inscripcionEstandar_1 = new InscripcionEstandar();
    Participante _participante_1 = new Participante(_jugador_1, _inscripcionEstandar_1);
    Participante part2 = _participante_1;
    Jugador _jugador_2 = new Jugador("Juan", 27);
    InscripcionEstandar _inscripcionEstandar_2 = new InscripcionEstandar();
    Participante _participante_2 = new Participante(_jugador_2, _inscripcionEstandar_2);
    Participante part3 = _participante_2;
    Jugador _jugador_3 = new Jugador("Alberto", 20);
    InscripcionEstandar _inscripcionEstandar_3 = new InscripcionEstandar();
    Participante _participante_3 = new Participante(_jugador_3, _inscripcionEstandar_3);
    Participante part4 = _participante_3;
    Jugador _jugador_4 = new Jugador("Fabio", 20);
    InscripcionEstandar _inscripcionEstandar_4 = new InscripcionEstandar();
    Participante _participante_4 = new Participante(_jugador_4, _inscripcionEstandar_4);
    Participante part5 = _participante_4;
    Jugador _jugador_5 = new Jugador("Alejo", 26);
    InscripcionEstandar _inscripcionEstandar_5 = new InscripcionEstandar();
    Participante _participante_5 = new Participante(_jugador_5, _inscripcionEstandar_5);
    Participante part6 = _participante_5;
    Jugador _jugador_6 = new Jugador("Casio", 29);
    InscripcionEstandar _inscripcionEstandar_6 = new InscripcionEstandar();
    Participante _participante_6 = new Participante(_jugador_6, _inscripcionEstandar_6);
    Participante part7 = _participante_6;
    Jugador _jugador_7 = new Jugador("Alan", 30);
    InscripcionEstandar _inscripcionEstandar_7 = new InscripcionEstandar();
    Participante _participante_7 = new Participante(_jugador_7, _inscripcionEstandar_7);
    Participante part8 = _participante_7;
    Jugador _jugador_8 = new Jugador("Carlos", 20);
    InscripcionEstandar _inscripcionEstandar_8 = new InscripcionEstandar();
    Participante _participante_8 = new Participante(_jugador_8, _inscripcionEstandar_8);
    Participante part9 = _participante_8;
    Jugador _jugador_9 = new Jugador("Lucas", 20);
    InscripcionEstandar _inscripcionEstandar_9 = new InscripcionEstandar();
    Participante _participante_9 = new Participante(_jugador_9, _inscripcionEstandar_9);
    Participante part10 = _participante_9;
    part1.inscribirse(partidoEstandar);
    part2.inscribirse(partidoEstandar);
    part3.inscribirse(partidoEstandar);
    part4.inscribirse(partidoEstandar);
    part5.inscribirse(partidoEstandar);
    part6.inscribirse(partidoEstandar);
    part7.inscribirse(partidoEstandar);
    part8.inscribirse(partidoEstandar);
    part9.inscribirse(partidoEstandar);
    part10.inscribirse(partidoEstandar);
    return partidoEstandar;
  }
  
  public static Partido crearPartidoCon9Estandar() {
    Date _date = new Date();
    Partido _partido = new Partido(_date);
    Partido partido = _partido;
    Jugador _jugador = new Jugador("Pepe", 20);
    InscripcionEstandar _inscripcionEstandar = new InscripcionEstandar();
    Participante _participante = new Participante(_jugador, _inscripcionEstandar);
    Participante part1 = _participante;
    Jugador _jugador_1 = new Jugador("Luis", 35);
    InscripcionEstandar _inscripcionEstandar_1 = new InscripcionEstandar();
    Participante _participante_1 = new Participante(_jugador_1, _inscripcionEstandar_1);
    Participante part2 = _participante_1;
    Jugador _jugador_2 = new Jugador("Juan", 27);
    InscripcionEstandar _inscripcionEstandar_2 = new InscripcionEstandar();
    Participante _participante_2 = new Participante(_jugador_2, _inscripcionEstandar_2);
    Participante part3 = _participante_2;
    Jugador _jugador_3 = new Jugador("Alberto", 20);
    InscripcionEstandar _inscripcionEstandar_3 = new InscripcionEstandar();
    Participante _participante_3 = new Participante(_jugador_3, _inscripcionEstandar_3);
    Participante part4 = _participante_3;
    Jugador _jugador_4 = new Jugador("Fabio", 20);
    InscripcionEstandar _inscripcionEstandar_4 = new InscripcionEstandar();
    Participante _participante_4 = new Participante(_jugador_4, _inscripcionEstandar_4);
    Participante part5 = _participante_4;
    Jugador _jugador_5 = new Jugador("Alejo", 26);
    InscripcionEstandar _inscripcionEstandar_5 = new InscripcionEstandar();
    Participante _participante_5 = new Participante(_jugador_5, _inscripcionEstandar_5);
    Participante part6 = _participante_5;
    Jugador _jugador_6 = new Jugador("Casio", 29);
    InscripcionEstandar _inscripcionEstandar_6 = new InscripcionEstandar();
    Participante _participante_6 = new Participante(_jugador_6, _inscripcionEstandar_6);
    Participante part7 = _participante_6;
    Jugador _jugador_7 = new Jugador("Alan", 30);
    InscripcionEstandar _inscripcionEstandar_7 = new InscripcionEstandar();
    Participante _participante_7 = new Participante(_jugador_7, _inscripcionEstandar_7);
    Participante part8 = _participante_7;
    Jugador _jugador_8 = new Jugador("Carlos", 20);
    InscripcionEstandar _inscripcionEstandar_8 = new InscripcionEstandar();
    Participante _participante_8 = new Participante(_jugador_8, _inscripcionEstandar_8);
    Participante part9 = _participante_8;
    part1.inscribirse(partido);
    part2.inscribirse(partido);
    part3.inscribirse(partido);
    part4.inscribirse(partido);
    part5.inscribirse(partido);
    part6.inscribirse(partido);
    part7.inscribirse(partido);
    part8.inscribirse(partido);
    part9.inscribirse(partido);
    return partido;
  }
  
  public static Partido crearPartidoCon8Estandar() {
    Date _date = new Date();
    Partido _partido = new Partido(_date);
    Partido partido = _partido;
    Jugador _jugador = new Jugador("Pepe", 20);
    InscripcionEstandar _inscripcionEstandar = new InscripcionEstandar();
    Participante _participante = new Participante(_jugador, _inscripcionEstandar);
    Participante part1 = _participante;
    Jugador _jugador_1 = new Jugador("Luis", 35);
    InscripcionEstandar _inscripcionEstandar_1 = new InscripcionEstandar();
    Participante _participante_1 = new Participante(_jugador_1, _inscripcionEstandar_1);
    Participante part2 = _participante_1;
    Jugador _jugador_2 = new Jugador("Juan", 27);
    InscripcionEstandar _inscripcionEstandar_2 = new InscripcionEstandar();
    Participante _participante_2 = new Participante(_jugador_2, _inscripcionEstandar_2);
    Participante part3 = _participante_2;
    Jugador _jugador_3 = new Jugador("Alberto", 20);
    InscripcionEstandar _inscripcionEstandar_3 = new InscripcionEstandar();
    Participante _participante_3 = new Participante(_jugador_3, _inscripcionEstandar_3);
    Participante part4 = _participante_3;
    Jugador _jugador_4 = new Jugador("Fabio", 20);
    InscripcionEstandar _inscripcionEstandar_4 = new InscripcionEstandar();
    Participante _participante_4 = new Participante(_jugador_4, _inscripcionEstandar_4);
    Participante part5 = _participante_4;
    Jugador _jugador_5 = new Jugador("Alejo", 26);
    InscripcionEstandar _inscripcionEstandar_5 = new InscripcionEstandar();
    Participante _participante_5 = new Participante(_jugador_5, _inscripcionEstandar_5);
    Participante part6 = _participante_5;
    Jugador _jugador_6 = new Jugador("Casio", 29);
    InscripcionEstandar _inscripcionEstandar_6 = new InscripcionEstandar();
    Participante _participante_6 = new Participante(_jugador_6, _inscripcionEstandar_6);
    Participante part7 = _participante_6;
    Jugador _jugador_7 = new Jugador("Alan", 30);
    InscripcionEstandar _inscripcionEstandar_7 = new InscripcionEstandar();
    Participante _participante_7 = new Participante(_jugador_7, _inscripcionEstandar_7);
    Participante part8 = _participante_7;
    part1.inscribirse(partido);
    part2.inscribirse(partido);
    part3.inscribirse(partido);
    part4.inscribirse(partido);
    part5.inscribirse(partido);
    part6.inscribirse(partido);
    part7.inscribirse(partido);
    part8.inscribirse(partido);
    return partido;
  }
}
